export enum KeyEventEnum {
  FORWARD = 'FORWARD',
  BACKWARD = 'BACKWARD',
  LEFT = 'LEFT',
  RIGHT = 'RIGHT',
  CAMERA_FOCUS = 'FOCUS',
  CAMERA_FOLLOW = 'FOLLOW',
  LAND = 'LAND',
  TAKE_OFF = 'TAKE_OFF',
  ENTER = 'ENTER',
  FUEL = 'FUEL',
}
