export enum KeyEventEnum {
  FORWARD = 'FORWARD',
  BACKWARD = 'BACKWARD',
  LEFT = 'LEFT',
  RIGHT = 'RIGHT',
  PLAYER_FOCUS = 'FOCUS',
  CAMERA = 'CAMERA',
  LAND_OR_TAKE_OFF = 'LAND_OR_TAKE_OFF',
  ENTER = 'ENTER',
  FUEL = 'FUEL',
  HELP = 'HELP',
}
